GET http://localhost:8080/articles/5e4d3bb338e522495d850bc0
###########################################
GET http://localhost:8080/articles

###########################################
GET http://localhost:8080/championnats

#################################
GET http://localhost:8080/championnats?name=Ligue%201

#################################
GET http://localhost:8080/articles?championnat=2021

#################################
GET http://localhost:8080/teams?team=2015

#################################
GET http://localhost:8080/clubs?club=satde-de-reims