GET http://localhost:8080/articles/5e4d3bb338e522495d850bc0
###########################################
GET http://localhost:8080/articles

###########################################
GET http://localhost:8080/championnats

#################################
GET http://localhost:8080/championnats?url=premier-league

#################################
GET http://localhost:8080/articles?championnat=2021

#################################
GET http://localhost:8080/teams?team=2021

#################################
GET http://localhost:8080/clubs?club=nimes-olympique

#################################
DELETE http://localhost:8080/articles/5e55000dcac217237498c5ea

#################################
PATCH  http://localhost:8080/users/5e5677453935863808ef5efd
Content-type: application/json

{
    "name": "John Doe",
    "email": "john@example.com"
}
