GET http://localhost:8080/articles/5e4d3bb338e522495d850bc0
###########################################
GET http://localhost:8080/articles

###########################################
GET http://localhost:8080/championnats

#################################
GET http://localhost:8080/championnats?name=Ligue%201

#################################
GET http://localhost:8080/articles?championnat=2021

#################################
GET http://localhost:8080/teams?team=2015

#################################
GET http://localhost:8080/clubs?club=satde-de-reims
############################################
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "name": "fefvndfvndfefmardi1",
  "email": "fefz cx fzmardi1@example.com",
  "password": "mardi1"
}
##############################
POST http://localhost:8080/users/auth
Content-Type: application/json

{
  "email": "petitbogoss@example.com",
  "password": "bogoss13"
}